//
//  Icon.swift
//  Steadingomatic
//
//  Created by Keith Avery on 2/23/16.
//  Copyright © 2016 Keith Avery. All rights reserved.
//

import Foundation
enum Icon: String {
    case Acorn = "\u{f007}"
    case AntelopePassant = "\u{f006}"
    case AntelopeRampantDemonic = "a"
    case AntelopeStatant = "b"
    case Ape = "c"
    case ApeCollaredAndChained = "e"
    case ArmEmbowedInArmor = "\u{f036}"
    case ArmHabitedAndCoupedAtTheElbow = "\u{f01f}"
    case Bat = "f"
    case BearPassant = "g"
    case BearRampant = "h"
    case BearSejeantErect = "i"
    case BearStatnt = "\u{f008}"
    case BearsHeadCouped = "j"
    case BearsHeadCoupedEnglish = "\u{f005}"
    case BearsHeadErasedAndMuzzled = "k"
    case BeeVolant = "l"
    case BoarPassant = "m"
    case BoarRampant = "n"
    case BoarStatant = "o"
    case BoarsHeadCouped = "p"
    case BoarsHeadErased = "q"
    case BordureInvected = "r"
    case BordureNebuly = "s"
    case BordurePotenty = "t"
    case BordureWavy = "u"
    case BucksHeadCouped = "v"
    case BullPassant = "w"
    case BullRampant = "x"
    case BullsHeadCaboshed = "y"
    case CatherineWheel = "z"
    case Censer = "\u{f028}"
    case Centaur = "A"
    case Chapeau = "B"
    case ChevalierOnHorseback = "C"
    case Cock = "D"
    case ConeyPassant = "E"
    case Conquefoil = "F"
    case Coronet = "G"
    case DogHead = "\u{f034}"
    case DolphinHauriant = "H"
    case DolphinNaiant = "I"
    case DucalCoronet = "J"
    case EagleClose = "K"
    case EagleDisplayed = "L"
    case EagleDisplayedWingsInverted = "M"
    case EagleDoubleHeaded = "N"
    case EagleRising = "O"
    case EagleRisingWingsAddorsed = "P"
    case EagleRisingWingsElevatedAddorsed = "Q"
    case EagleRisingWingsInverted = "R"
    case EaglesHeadCouped = "S"
    case EaglesHeadErased = "T"
    case ElephantAndCastle = "U"
    case Enfield = "V"
    case Escallop = "\u{f035}"
    case Estoile = "W"
    case Falcon = "X"
    case Fleece = "Y"
    case FleurDeLis = "Z"
    case FoxPassant = "0"
    case FoxSejeant = "1"
    case Garb = "2"
    case GoatSalient = "3"
    case Goutte = "\u{f033}"
    case HandDexter = "\u{f031}"
    case HandSinister = "\u{f032}"
    case HareSalient = "4"
    case HeraldicAntelopePassant = "5"
    case HeraldicAntelopeRampant = "6"
    case HeraldicTigerPassant = "7"
    case HeraldicTigerRampant = "8"
    case Heron = "9"
    case Hind = "!"
    case HorsePassant = "'"
    case HorseRampant = "#"
    case Keys = "\u{f030}"
    case LeopardHeadErased = "$"
    case LeopardPassant = "%"
    case LeopardRampant = "&"
    case LeopardsFace = "\""
    case LionRampantRegardant = "\u{f02a}"
    case LionSalient = "\u{f02b}"
    case LionSejant = "\u{f02d}"
    case LionSejantRegardantErect = "\u{f02c}"
    case LionSejantRegardant = "\u{f02e}"
    case LionStatant = "\u{f02f}"
    case Looped = "\u{f029}"
    case LynxCoward = "("
    case Martlet = ")"
    case MartletVolant = "*"
    case Mermaid = "+"
    case Merman = ","
    case Mullet = "-"
    case Mullet1 = "."
    case MulletOf6Points = "/"
    case MulletOfPoints = ":"
    case OakTree = "<"
    case Ostrich = "="
    case Otter = ">"
    case Owl = "?"
    case Pegasus = "d"
    case PegasusPassant = "@"
    case PegasusRampant = "["
    case Popinjay = "]"
    case Quatrefoil = "^"
    case RamRampant = "_"
    case RamSkull = "\u{f026}"
    case RamStatant = "`"
    case RamsHeadCaboshed = "{"
    case Raven = "|"
    case Reindeer =    "}"
    case Rose = "~"
    case RoseSlippedAndLeaved = "\\"
    case SalmonHauriant = "\u{f000}"
    case SalmonNaiant = "\u{f001}"
    case SeaHorse = "\u{f002}"
    case SeadogRampant = "\u{f024}"
    case Seahog = "\u{f023}"
    case SerpentNowed = "\u{f003}"
    case SheepPassant = "\u{f009}"
    case ShipUnderSail = "\u{f00a}"
    case Sphinx = "\u{f00b}"
    case Squirrel = "\u{f00c}"
    case StagAtGaze = "\u{f00d}"
    case StagLodged = "\u{f00e}"
    case StagSpringing = "\u{f00f}"
    case StagStatant = "\u{f010}"
    case StagTrippant = "\u{f011}"
    case SunInSplendor = "\u{f012}"
    case Swan = "\u{f013}"
    case SwordScimitar = "\u{f025}"
    case TalbotPassant = "\u{f014}"
    case TalbotRampant = "\u{f015}"
    case TalbotSejeant = "\u{f016}"
    case Thistle = "\u{f017}"
    case Tower = "\u{f022}"
    case TowerTriple = "\u{f020}"
    case Trefoil = "\u{f027}"
    case WolfCourant = "\u{f018}"
    case WolfPassant = "\u{f019}"
    case WolfRampant = "\u{f01a}"
    case WolfSalient = "\u{f01b}"
    case WolfStatant = "\u{f01c}"
    case Yale = "\u{f01d}"
    case YaleSejantErect = "\u{f01e}"
    case Ypotryll = "\u{f021}"
    
    static func allValues() -> [String] {
        return ["\u{f007}","\u{f006}","a","b","c","e","\u{f036}","\u{f01f}","f","g","h","i","\u{f008}","j","\u{f005}",
            "k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","\u{f028}","A","B","C","D","E","F","G",
            "\u{f034}","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","\u{f035}","W","X","Y","Z","0",
            "1","2","3","\u{f033}","\u{f031}","\u{f032}","4","5","6","7","8","9","!","'","#","\u{f030}","$","%","&",
            "\"","\u{f02a}","\u{f02b}","\u{f02d}","\u{f02c}","\u{f02e}","\u{f02f}","\u{f029}","(",")","*","+",
            ",","-",".","/",":","<","=",">","?","d","@","[","]","^","_","\u{f026}","`","{","|","}","~","\\",
            "\u{f000}","\u{f001}","\u{f002}","\u{f024}","\u{f023}","\u{f003}","\u{f009}","\u{f00a}","\u{f00b}",
            "\u{f00c}","\u{f00d}","\u{f00e}","\u{f00f}","\u{f010}","\u{f011}","\u{f012}","\u{f013}","\u{f025}",
            "\u{f014}","\u{f015}","\u{f016}","\u{f017}","\u{f022}","\u{f020}","\u{f027}","\u{f018}","\u{f019}",
            "\u{f01a}","\u{f01b}","\u{f01c}","\u{f01d}","\u{f01e}","\u{f021}"]
    }
    static func pick() -> Icon {
        // pick and return a new value
        let rand = arc4random_uniform(UInt32(Icon.allValues().count))
        return Icon(rawValue: Icon.allValues()[Int(rand)])!
    }
    
}